### ISSUE TITLE
screenshot script (Deathemonic ) for wayland

### ISSUE THREAD

**Issue by EliaHKM** [catppuccin/rofi#18]
Hi🙋🏻,
I've installed  rofi (Deathemonic)
on but the screenshot doesn't 
produce any picture
I tried the command inside the script
it gives me black screenshot
so could make wayland version for 
screenshot?
thanks in advance

**Comment by justTOBBI** [comment]
Hey, as I currently dont use a wm anymore you could open a PR with wayland commands.
You would just have to change the script to wayland replacements.

**Comment by EliaHKM** [comment]
actually I've asked my question here
because I'm stuck with grim, grimblast and grimshot
all of them are good but I don't how to make them
take a screenshot and send it to the Screenshots directory 
I tried replacing xclip with wl-clipboard
but nothing happen it just drop the screenshot
in  my home directory 

thanks again
