### ISSUE TITLE
Nerd Fonts Issue in Basic Config

### ISSUE THREAD

**Issue by IQubic** [catppuccin/rofi#23]
So, the basic config, located at `basic/.config/rofi/config.rasi` still uses codepoint `fa5f`. It's showing up as a box with that hex code on my system. I've checked my system, and I do have Hack Nerdfonts v 3.2.1 installed:
![2024-06-19_14-32-04](https://github.com/catppuccin/rofi/assets/22628816/69b9f349-3e40-4a49-8270-363c4bf09025)

I've looked at the official Nerdfont website, and it looks like this window glyph might actually have been moved to codepoint `f0570`. I know that there was a recent update to fix the nerdfonts, but that only seems to have changed files in the `deathemonics` folder.
![2024-06-19_14-38-29](https://github.com/catppuccin/rofi/assets/22628816/864c0444-c106-4551-9e37-295815705e99)

**Comment by IQubic** [comment]
As the text on the official Nerdfonts website says, this change was introduced with v3.0.0. If this theme port is set to work with v3.2.1, the basic config should be updated to actually work with these new codepoints.

**Comment by sgoudham** [comment]
Happy to accept a PR updating the icons to the version on the README :+1:

**Comment by nonetrix** [comment]
Oops I am not sure why it didn't get picked up my bad
