### ISSUE TITLE
Failed to open theme

### ISSUE THREAD

**Issue by federico-ntr** [catppuccin/rofi#5]
Yesterday I installed rofi and this theme on EndeavourOS + Gnome and everything worked fine. I also set up a shortcut to run `rofi -show drun` when pressing `super`+`D`.

This morning I turned on my computer and the shortcut leads to an error `Failed to open theme: /home/username/.config/rofi/catppuccin Error: No such file or directory`.

Weirdly enough, if I run `rofi -show drun` on terminal everything is fine, only the shortcut is broken, but only with this theme.

Also selecting the theme with `rofi-theme-selector` leads to a broken theme. Unfortunately I'm unable to take screenshots.

**Comment by nekowinston** [comment]
Closing this, since the theme has been repository has been reworked multiple times since this issue has been opened; starting with the port to 0.2.0 since a922e6ca60b4df8c2f4eebb91ad487b3aa4f8518.

Please create a new issue, should the problem still exist.
